### ISSUE TITLE
[Release Size] Radiant Node v1.1.2 

### ISSUE THREAD

**Issue by nguyenvinhlinh** [RadiantBlockchain/radiant-node#3]
I think the release size of radiant node v.1.1.2 is quite big compare to its previous releases. 

![image](https://user-images.githubusercontent.com/5039272/186689269-2b908b0d-e0cb-40d1-ae36-fc70158d6b6e.png)

As you can see, the size of `https://radiant-node-v1.1.2-ubuntu2004.zip` is more then 1.1GB. I think there is a publishing issue!

**Comment by RadiantBlockchain** [comment]
Thank you
