### ISSUE TITLE
zmq pub sub not available

### ISSUE THREAD

**Issue by snoby** [RadiantBlockchain/radiant-node#8]
Building natively and in a dockerfile results in a radiant node build that does not have zmq enabled.
This is the build commands that i have used

```
 1803  cmake -GNinja .. -DBUILD_RADIANT_QT=off
 1804  ninja -j0
```

I've verified this with the following start up command line:
```
./radiantd -conf=$PWD/radiant_dev.conf -zmqpubhashblock=tcp://127.0.0.1:29000
```

I've verified there are no zmq commands in radiant-cli help...

I've also verified there is no zmq ports open with the following  lsof grep command
```
 sudo lsof -i -P -n | grep 'radiantd.*LISTEN'
radiantd  398093           snoby    9u  IPv6 2244808      0t0  TCP *:17332 (LISTEN)
radiantd  398093           snoby   27u  IPv6 2244813      0t0  TCP *:17333 (LISTEN)
radiantd  398093           snoby   28u  IPv4 2244814      0t0  TCP *:17333 (LISTEN)
radiantd  398093           snoby   29u  IPv4 2244815      0t0  TCP 127.0.0.1:17334 (LISTEN)
```

Searching the build output i can see the the src/zmq/libzmq.a has been built.  and searching the CMAKECache.txt file I see we have links to the libzmwq.so
```
./CMakeCache.txt:45:BUILD_RADIANT_ZMQ:BOOL=ON
./CMakeCache.txt:516:ZeroMQ_zmq_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libzmq.so
./CMakeCache.txt:630:zmq_BINARY_DIR:STATIC=/data/radiant_work/radiant_node_src/radiant-node/build/src/zmq
./CMakeCache.txt:633:zmq_IS_TOP_LEVEL:STATIC=OFF
./CMakeCache.txt:636:zmq_SOURCE_DIR:STATIC=/data/radiant_work/radiant_node_src/radiant-node/src/zmq
./CMakeCache.txt:892://Details about finding ZeroMQ_zmq
./CMakeCache.txt:893:FIND_PACKAGE_MESSAGE_DETAILS_ZeroMQ_zmq:INTERNAL=[/usr/lib/x86_64-linux-gnu/libzmq.so][/usr/include]
./CMakeCache.txt:1101://ADVANCED property for variable: ZeroMQ_zmq_LIBRARY
./CMakeCache.txt:1102:ZeroMQ_zmq_LIBRARY-ADVANCED:INTERNAL=1

```

I'm happy to be wrong here, but I'm out of ideas on what to check for next.

Find below my config file
```
cat radiant_dev.conf
rpcworkqueue=32
rpcthreads=16
rest=1
server=1
rpcallowip=0.0.0.0/0
txindex=1
rpcuser=dockeruser
rpcpassword=dockerpass
testnet=1
datadir=/data/raddata

[test]
wallet=/data/testnet_wallets


```

**Comment by RadiantBlockchain** [comment]
Thank you for the report. Perhaps this is a problem with the ZMQ libs in the docker. We will test and report back if ZMQ is enabled on a native build.

**Comment by snoby** [comment]
Oh it's enabled on the native build with the same result.

**Comment by snoby** [comment]
@RadiantBlockchain  - can you please take a swing at this?  I know the same libraries work for these notification in geth.

**Comment by RadiantBlockchain** [comment]
@snoby Looking into it, thank you

**Comment by snoby** [comment]
@RadiantBlockchain  - hi, 4 months later anything?

**Comment by snoby** [comment]
Here we are  April 12, 2024... after doing some back channeling this is how you enable zmq
cmake -DBUILD_BITCOIN_ZMQ=ON
